[package]
name = "reco"
version = "0.1.0"
authors = ["Wave View Imaging"]
edition = "2018"
publish = false

[dependencies]
regex = "1.4.5"
lazy_static = "1.4.0"
thiserror = "1.0.24"

[dev-dependencies]
approx = "0.4.0"
