name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    name: Rust stable, benchmark
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: cargo build --verbose
      - name: Run bench
        run: cargo bench
