name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    [cron: "0 12 * * 0"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Lint
        run: cargo clippy --verbose
