name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    [cron: "0 12 * * 0"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8]
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r dev-requirements.txt
      - run: pip install -e .
      - name: Test
        run: nosetests --traverse-namespace ffi/python/tests
